[project]
name = "evalon-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GitHub Actions Bot", email = "github-actions@github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "evalon[providers]",
]

[project.scripts]
evalon-quickstart = "evalon_quickstart:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
evalon = { workspace = true }
